from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Taxis(object):
    def setupUi(self, Taxis):
        Taxis.setObjectName("Taxis")
        Taxis.resize(235, 319)
        Taxis.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        Taxis.setStyleSheet("background-color: rgb(203, 135, 0);")
        Taxis.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        Taxis.setAnimated(True)
        Taxis.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Taxis)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 214, 287))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblKm = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblKm.setFont(font)
        self.lblKm.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lblKm.setObjectName("lblKm")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblKm)
        self.spnKm = QtWidgets.QSpinBox(self.widget)
        self.spnKm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spnKm.setObjectName("spnKm")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spnKm)
        self.lblEspera = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblEspera.setFont(font)
        self.lblEspera.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lblEspera.setObjectName("lblEspera")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblEspera)
        self.spnEspera = QtWidgets.QSpinBox(self.widget)
        self.spnEspera.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spnEspera.setObjectName("spnEspera")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spnEspera)
        self.lblDemora = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblDemora.setFont(font)
        self.lblDemora.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lblDemora.setObjectName("lblDemora")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblDemora)
        self.spnDemora = QtWidgets.QSpinBox(self.widget)
        self.spnDemora.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spnDemora.setObjectName("spnDemora")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spnDemora)
        self.lblTipoasiento = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblTipoasiento.setFont(font)
        self.lblTipoasiento.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lblTipoasiento.setObjectName("lblTipoasiento")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblTipoasiento)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("Primera")
        self.comboBox.addItem("Economica")
        self.comboBox.addItem("Turista")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblCostoPrimerKm = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblCostoPrimerKm.setFont(font)
        self.lblCostoPrimerKm.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lblCostoPrimerKm.setObjectName("lblCostoPrimerKm")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblCostoPrimerKm)
        self.lblPrimerKm = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPrimerKm.setFont(font)
        self.lblPrimerKm.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lblPrimerKm.setObjectName("lblPrimerKm")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblPrimerKm)
        self.lblMontoKm = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblMontoKm.setFont(font)
        self.lblMontoKm.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lblMontoKm.setObjectName("lblMontoKm")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblMontoKm)
        self.lblTotalKm = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalKm.setFont(font)
        self.lblTotalKm.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lblTotalKm.setObjectName("lblTotalKm")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lblTotalKm)
        self.lblMontoEspera = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblMontoEspera.setFont(font)
        self.lblMontoEspera.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lblMontoEspera.setObjectName("lblMontoEspera")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblMontoEspera)
        self.lblTotalEspera = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalEspera.setFont(font)
        self.lblTotalEspera.setStyleSheet("background-color: rgb(172, 172, 172);\n"
"\n"
"")
        self.lblTotalEspera.setObjectName("lblTotalEspera")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblTotalEspera)
        self.lblMontoDemora = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblMontoDemora.setFont(font)
        self.lblMontoDemora.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lblMontoDemora.setObjectName("lblMontoDemora")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblMontoDemora)
        self.lblTotalDemora = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalDemora.setFont(font)
        self.lblTotalDemora.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lblTotalDemora.setObjectName("lblTotalDemora")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lblTotalDemora)
        self.lblTotal = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblTotal.setFont(font)
        self.lblTotal.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lblTotal.setObjectName("lblTotal")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblTotal)
        self.lblTotalPagar = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalPagar.setFont(font)
        self.lblTotalPagar.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lblTotalPagar.setObjectName("lblTotalPagar")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lblTotalPagar)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCalcular = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnCalcular.setFont(font)
        self.btnCalcular.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.btnCalcular.setObjectName("btnCalcular")
        self.horizontalLayout.addWidget(self.btnCalcular)
        self.btnLimpiar = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnLimpiar.setFont(font)
        self.btnLimpiar.setStyleSheet("background-color: rgb(229, 0, 0);")
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.horizontalLayout.addWidget(self.btnLimpiar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        Taxis.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Taxis)
        self.statusbar.setObjectName("statusbar")
        Taxis.setStatusBar(self.statusbar)

        self.retranslateUi(Taxis)
        self.btnLimpiar.clicked.connect(self.spnDemora.clear) # type: ignore
        self.btnLimpiar.clicked.connect(self.spnEspera.clear) # type: ignore
        self.btnLimpiar.clicked.connect(self.spnKm.clear) # type: ignore
        self.btnLimpiar.clicked.connect(self.comboBox.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Taxis)

        self.btnCalcular.clicked.connect(self.onClick)
    def retranslateUi(self, Taxis):
        _translate = QtCore.QCoreApplication.translate
        Taxis.setWindowTitle(_translate("Taxis", "MainWindow"))
        self.label_5.setText(_translate("Taxis", "Taxis Tarifa"))
        self.lblKm.setText(_translate("Taxis", "Km Viajel"))
        self.lblEspera.setText(_translate("Taxis", "Espera"))
        self.lblDemora.setText(_translate("Taxis", "Demora"))
        self.lblTipoasiento.setText(_translate("Taxis", "Tipo de asiento"))
        self.lblCostoPrimerKm.setText(_translate("Taxis", "Costo primer Km"))
        self.lblPrimerKm.setText(_translate("Taxis", "0"))
        self.lblMontoKm.setText(_translate("Taxis", "Monto Km"))
        self.lblTotalKm.setText(_translate("Taxis", "0"))
        self.lblMontoEspera.setText(_translate("Taxis", "Monto espera"))
        self.lblTotalEspera.setText(_translate("Taxis", "0"))
        self.lblMontoDemora.setText(_translate("Taxis", "Monto demora"))
        self.lblTotalDemora.setText(_translate("Taxis", "0"))
        self.lblTotal.setText(_translate("Taxis", "Total"))
        self.lblTotalPagar.setText(_translate("Taxis", "0"))
        self.label.setText(_translate("Taxis", "Iva"))
        self.label_4.setText(_translate("Taxis", "13%"))
        self.btnCalcular.setText(_translate("Taxis", "Continuar"))
        self.btnLimpiar.setText(_translate("Taxis", " Borrar todo"))

    def onClick(self):

        km = int(self.spnKm.value())
        espera = int(self.spnEspera.value())
        demora = int(self.spnDemora.value())

        if self.comboBox.currentIndex() == 0:
            tarifaPrimerKm = 1000 * 0.60
            tarifaKmAdicional = 1500
            tarifaDemora = 2000
            tarifaEspera = 2500

        elif self.comboBox.currentIndex() == 1:
            tarifaPrimerKm = 1000
            tarifaKmAdicional = 1500
            tarifaDemora = 2000
            tarifaEspera = 2500

        else:
            tarifaPrimerKm = 1000 * 0.80
            tarifaKmAdicional = 1500
            tarifaDemora = 2000
            tarifaEspera = 2500
        iva = 0.13
        kmViaje = km - 1
        montoKmAdicionales = kmViaje * tarifaKmAdicional
        montoDemora = demora * tarifaDemora
        montoEspera = espera * tarifaEspera
        totalPagar = tarifaPrimerKm + montoKmAdicionales + montoEspera + montoDemora * iva
        self.lblPrimerKm.setText("¢" + str(tarifaPrimerKm))
        self.lblTotalKm.setText("¢" + str(montoKmAdicionales))
        self.lblTotalDemora.setText("¢" + str(montoDemora))
        self.lblTotalEspera.setText("¢" + str(montoEspera))
        self.lblTotalPagar.setText("¢" + str(totalPagar))